# Generated by Django 5.0.1 on 2024-01-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Augment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('two_one', models.DecimalField(decimal_places=2, max_digits=3)),
                ('three_two', models.DecimalField(decimal_places=2, max_digits=3)),
                ('four_one', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
