# Generated by Django 4.1 on 2024-01-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='augment',
            name='four_one',
        ),
        migrations.RemoveField(
            model_name='augment',
            name='three_two',
        ),
        migrations.RemoveField(
            model_name='augment',
            name='two_one',
        ),
        migrations.AddField(
            model_name='augment',
            name='avg_four_two',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='augment',
            name='avg_three_two',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='augment',
            name='avg_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='augment',
            name='avg_two_one',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='augment',
            name='games_four_two',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='augment',
            name='games_three_two',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='augment',
            name='games_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='augment',
            name='games_two_one',
            field=models.IntegerField(default=0),
        ),
    ]
