# Generated by Django 4.1 on 2024-01-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_remove_augment_four_one_remove_augment_three_two_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('augments', models.ManyToManyField(to='stats.augment')),
            ],
        ),
    ]
