# Generated by Django 4.2.9 on 2024-01-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_alter_augment_avg_four_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='augment',
            name='avg_four_two',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='augment',
            name='avg_three_two',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='augment',
            name='avg_total',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='augment',
            name='avg_two_one',
            field=models.FloatField(default=None),
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
